### ISSUE TITLE
M5Stack initialization failure

### ISSUE THREAD

**Issue by sagakk** [sakura-internet/sipf-std-client_sample_m5stack#2]
◆Content of the problem
It is a phenomenon that does not start. When I check it on the serial monitor, it stops at "M5Stack Initializing ...".

◆Operating environment
M5Stack Basic , M5Stack Gray

◆Contents to be corrected
Just comment out "Serial.begin(115200);" in the setup function.

**Comment by f-okuhara** [comment]
Arduinoのボード定義が古い可能性があります。
[M5Stack公式の手順](https://docs.m5stack.com/en/arduino/arduino_development)に従い、ボード定義とライブラリをインストールしなおした後、スケッチのビルドをお試しください。

私達の開発中にも最新のライブラリとEspressif提供のESP32のボード定義にあるM5Stackの定義の組み合わせでLCDのバックライトが一瞬点灯したのち起動しない現象が出ていました。
M5Stack提供のボード定義( https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/arduino/package_m5stack_index.json )とライブラリのインストールで解決していおります。

お試しください。

**Comment by sagakk** [comment]
ご提示いただいた内容のとおり、ESP32のボード定義ではなくM5Stackのボード定義に変更し、
下記内容の環境で再度確認したところ、正常に起動しました。
どうもありがとうございました。

【動作確認環境について】
◆Arduino-IDE　version：1.8.15
・ボードマネージャでは、「M5Stackのバージョン1.0.7」を利用
・ライブラリマネージャでは、「M5Stackのバージョン0.3.2」を利用
